### PR TITLE
Replacement Notification System

### PR DESCRIPTION
**Pull request by ddakebono**
This system offers a replacement for the awful VRChat Hud message system, giving you a far nicely looking notification with title, description, and a icon. You can simply call NotificationSystem.EnqueueNotification to have it setup and be ready for usage.

This system should solve all major issues with VRChat Hud messages, like leaving worlds and having the text stuck.

### CODE REVIEW

**Comment by Myrkie** [comment]
gib requi

**Comment by ddakebono** [comment]
Myrkur's a nerd

**Comment by Myrkie** [comment]
bono bigger nerd

**Comment by cxaiverb** [comment]
You all have the nerdism

**Comment by AO554** [comment]
Ya'll nerds fr

**Comment by Myrkie** [comment]
gayo

**Pull request merged**
