### PR TITLE
Added the Ability to set an Icon for Toggles

### PR DESCRIPTION
**Pull request by Gamersven**
Hi Requi, 

i thought this "should" be in your Button API because you already had the Code for it in place.

Git is some *Magic* Stuff and i hope this is Acceptable.

Viele Grüße ^^

### CODE REVIEW

**Comment by RequiDev** [comment]
While you're at it, could you extend it to also add the ability to change the "off" icon?

**Comment by Gamersven** [comment]
Updated with iconOn and iconOff Options.
grafik

**Comment by RequiDev** [comment]
Due to how C# works, could you create a new overload instead of adding parameters? If this goes live all mods using AddToggle would complain because the method signature changed and it can't find the method it compiled against.

**Comment by Gamersven** [comment]
Added the requested overloads.

**Comment by RequiDev** [comment]
The same goes for constructors.

**Pull request merged**
